name: PHP

on:
    push: null
    pull_request: null

permissions: {}

concurrency:
    group: '${{ github.workflow }}-${{ github.ref }}'
    cancel-in-progress: true

jobs:
    unit_tests:
        name: 'PHP ${{ matrix.php }} / Symfony ${{ matrix.symfony_version }} / ${{ matrix.dependencies }} / Ubuntu'
        strategy:
            matrix:
                php:
                    - '8.0'
                    - '8.1'
                    - '8.2'
                dependencies:
                    - 'lowest'
                    - 'highest'
                symfony_version:
                    - '~5.4.9'
                    - '~6.0.9'
                    - '~6.1.0'
                include:
                    - php: '8.2'
                      dependencies: 'lowestest'
                      symfony_version: '~6.2.0'
                    - php: '8.2'
                      dependencies: 'highest'
                      symfony_version: '~6.2.0'
        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: ramsey/composer-install@v2
                with:
                    dependency-versions: ${{ matrix.dependencies }}
                    composer-options: '--with=symfony/console:${{ matrix.symfony_version }}'

            -   run: composer exec -- phpunit

    unit_tests_windows:
        name: 'PHP ${{ matrix.php }} tests / Windows'
        strategy:
            matrix:
                php:
                    - '8.0'
        runs-on: windows-2022

        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: 'curl'

            -   uses: ramsey/composer-install@v2
                with:
                    dependency-versions: highest

            -   run: composer exec -- phpunit

    static_analysis:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                include:
                    - php: '8.1'
                      symfony_version: '~6.1.0'
                      dependencies: 'highest'

        name: Static analysis
        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: ramsey/composer-install@v2
                with:
                    dependency-versions: ${{ matrix.dependencies }}
                    composer-options: '--with=symfony/console:${{ matrix.symfony_version }}'

            -   run: composer normalize --dry-run

            -   uses: actions/cache@v3
                with:
                    path: .php-cs-fixer.cache
                    key: php-cs-fixer-cache

            -   uses: actions/cache@v3
                with:
                    path: /tmp/phpstan
                    key: phpstan-cache

            -   run: composer run crunz:analyze
